### ISSUE TITLE
[RFC] Proposed initial approach

### ISSUE THREAD

**Issue by ba66e77** [hopeonesource/geospatial_posts#1]
I have an initial approach in mind that I'd like to get feedback on. There are two main points to the approach, described below.

# The proposal

## 1. Define MVP as allowing providers to select a notification radius when sending posts.

The full feature set described in the README includes allowing users to define their own location polygon regions, using Nominatim search to determine polygons from text descriptions (e.g., "Arlington county, VA"), and allowing providers to set a radius from their event for which to send notifications, as well as all the UI and architectural structures necessary to support these features.

Given that a) deploying this functionality is time sensitive, b) it's not clear from user research if all the functionality is desired, and c) the majority of use case which the team involved in discussions have been able to readily imagine are more point-and-radius based than polygon based, I propose we decide that MVP for this feature is to allow providers to set a notification radius from the location of their event and address the additional functionality as enhancements to be made in future development cycles.

## 2. Calculate distances using MySQL Spatial functionality.

In order to reduce the architectural complexity involved in using a separate Postgre database for that tool's GIS features, I propose we start with using MySQL's spatial features.  As we move forward, it may end up being necessary to modify this plan if MySQL turns out not to support the depth of GIS features we need, but initial research suggests that it will be [sufficient for at least the MVP point-and-radius calculations](http://marcgg.com/blog/2017/03/13/mysql-viewport-gis/).

### GIS information storage 

Within MySQL, we have a couple options for how to actually store the location information. [MySQL's spatial datatypes](https://dev.mysql.com/doc/refman/8.0/en/spatial-types.html) are the obvious pure-MySQL solution. However, these [data types are not currently supported by Drupal's DB API](https://www.drupal.org/project/drupal/issues/293483) and, since the entities to which this information will be attached is stored in Drupal, it will make our lives easier if Drupal is aware of these data fields.

One option is to patch Drupal core, as described in the issue linked above, so that Drupal is aware of the native Spatial data types. The downside of this is that it imposes a maintenance burden and could prove trickier to accomplish than we expect. It also means we would have to alter the fields currently in place on the Drupal user and the post entity.

The other option is to store the location data as text fields and use [MySQL's Spatial functions](https://dev.mysql.com/doc/refman/8.0/en/spatial-analysis-functions.html) to convert into and out of spatial data types. The downside of this approach is that it we lose the ability to use MySQL's spatial indexing features, so it will be slower to at least some degree.

My recommendation is to begin the work assuming we will store the data as text and convert in and out of spatial data types as needed. Once we have bench-marked the outcomes we can then determine if we need to go farther and try to patch core.

# Next steps

I'd like to hear what the larger group thinks of this approach and, at some point, we should come to a go/no-go decision.

Assuming this is a 'go', we'll need to know how the latitude and longitude are currently stored on the user and post objects in both the D8 and D7 instances so we can access that data as needed. It would also help to have access to a database dump of sample, sanitized data to work with as we develop.

**Comment by hopeonesource** [comment]
@ba66e77 I think we determined that we want to prioritize using polygons over than point-and-radius based to determine the areas the posts get sent to. Do you think you can do some research to see if MySQL can do point-in-polygon queries (ex. ST_CONTAINS) with complex polygons?  -Tom
