### ISSUE TITLE
Set-up Drupal 8 dev site

### ISSUE THREAD

**Issue by hopeonesource** [hopeonesource/geospatial_posts#4]
- [x] Reach out to HOS Drupal 8 team. 

Here are the Drupal 8 modules that are being planned to replace the Drupal 7 modules (https://docs.google.com/spreadsheets/d/1IbDSrl4V404eTlF6bjEBJ57y6y0nlfAwfsKQN4sWR3U/htmlview)

- [x] Review geospatial modules in Drupal 8

**Comment by d3netxer** [comment]
added instructions on setting-up Drupal 8 vanilla site in README file
